apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: hzz7v7jqx-python 
  janus-idp.io/tekton: hzz7v7jqx-python
  backstage.io/kubernetes-id: hzz7v7jqx-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hzz7v7jqx-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml