apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hzz7v7jqx-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hzz7v7jqx-python 
  name: hzz7v7jqx-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hzz7v7jqx-python 
